[package]
name = "rblib"
description = "Facade crate for backward compatibility. Alias of rblib-pipeline."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
exclude.workspace = true
publish = false

[lints]
workspace = true

[lib]
doctest = false

[features]
default = ["rblib-pipeline/default"]
jemalloc = ["rblib-pipeline/jemalloc"]
jemalloc-prof = ["rblib-pipeline/jemalloc-prof"]
optimism = ["rblib-pipeline/optimism"]
test-utils = ["rblib-pipeline/test-utils"]

[dependencies]
rblib-pipeline = { path = "../pipeline" }

[dev-dependencies]
rblib = { path = ".", features = ["test-utils"] }
eyre.workspace = true
serde.workspace = true
